@startuml DatabaseCommManagerImplementation

package edu.oakland.production.database {
    class DatabaseCommManagerImplementation {
        - DatabasePersistentStorage dps
        __
        + DatabaseCommManagerImplementation(DatabasePersistentStorage dps)
        .. Use Case 1 ..
        + int passGetRfidRequest()
        + LocationDataPoint passGetLocationDataPointRequest(int offset)
        + TrackData passGetTrackDataRequest(int offset)
        + void passStoreTrackDataRequest(TrackData trackData)
        + String passGetModeRequest()
    }
}

@enduml
