@startuml DisplayGpsInterfaceImplementation


package edu.oakland.production.display01 {
    class DisplayGpsInterfaceImplementation {
        - DisplayGpsReciever reciever
        __
        + DisplayGpsInterfaceImplementation(DisplayGpsReciever reciever)
        .. Use Case 1 ..
        + String receiveGpsSignal(Satellite satelliteSignal)
        .. Use Case 2 ..
        + SatelliteSignalCheckRequest reportGpsSignalLoss(Satellite satelliteSignal)
        + SatelliteSignalCheckRequest recheckSignalStength(Satellite satelliteSignal)
        + SatelliteSignalCheckRequest checkSignalStength(Satellite satelliteSignal)
        
    }
}

@enduml
