@startuml DatabaseGisManagerStub

package edu.oakland.test.database {
    class DatabaseGisManagerStub {
        __
        + void dataPointInIsDataPointOut
        + void currentSatGetsNextSat()
        + void modeInISModeOut()
        + void persistentStorageIsNotNull()
    }
}

@enduml