@startuml DatabaseCommManagerStub

package edu.oakland.test.database {
    class DatabaseCommManagerStub {
        __
        .. Use Case 1 ..
        + String receiveGpsSignalStrengths(Satellite satelliteSignal)
        .. Use Case 2 ..
        + PersistentStorageManager passGpsSignalStrength(String satelliteName)
    }
}

@enduml