@startuml TrackDataPlotterTests

package edu.oakland.test.display02 {
    class TrackDataPlotterTests {
        + void plotIsDisplayedWith5DataPoints()
        + void plotIsDisplayedWith1DataPoint()
        + void plotIsDisplayedWith2PlusDataPoints()
        + void nullTrackDataNotAllowed()
        + void zeroPointTrackDataNotAllowed() 
    }
}

@enduml
