@startuml Satellite

package edu.oakland.helper.admin {
    class Satellite {
        - String satelliteName
        - int strength
        + Satellite(String satelliteName, int strength)
        + String getSatelliteName()
        + int getStrength()
        + void setStrength(int strength)
        - boolean strengthIsValid(int strength)
    }
}

@enduml