@startuml SatelliteSignalCheckRequest

package edu.oakland.helper.display01 {
    class SatelliteSignalCheckRequest {
        + String getSatelliteName()
        + String getCheckType()
    }
}

@enduml