@startuml AdminTestPackage_Closure

package edu.oakland.test.admin {
    
}

!include LocationDataPointTests/LocationDataPointTests_Closure.puml
!include SatelliteTests/SatelliteTests_Closure.puml
!include TrackDataTests/TrackDataTests_Closure.puml

@enduml