@startuml SatelliteSignalCheckRequestTests

package edu.oakland.test.display01 {
  class SatelliteSignalCheckRequestTests {
    + void satelliteNameInIsSatelliteNameOut()
    + void checkTypeInIsCheckTypeOut()
    + void emptyNamesNotAllowed()
    + void emptyTypesNotAllowed()
    + void nullNamesNotAllowed()
    + void nullTypesNotAllowed()
  }
}

@enduml