@startuml DisplayGpsReceiverImplementationTests

package edu.oakland.test.display01 {
    class DisplayGpsReceiverImplementationTests {
        + void verifyReceiverCannotBeNull()
        + void signalInIsSignalOut()
        + void satelliteInIsSatelliteOutReportLoss()
        + void satelliteInIsSatelliteOutCheck()
        + void satelliteInIsSatelliteOutRecheck()
    }
}

@enduml
