@startuml DisplayGpsReceiverImplementationTests

package edu.oakland.test.display01 {
    class DisplayGpsReceiverImplementationTests {
        + void displayGpsManagerIsNotNull()
        + void measureGpsSignalStrengthSatelliteSignalIsNotNull()
        + void measureSignalSatelliteSignalIsNotNull() 
        + void measureGpsSignalStrengthSatelliteInIsSignalOut()
        + void measureSignalSignalInIsSignalOut()
    }
}

@enduml
