@startuml MiddlewareCommLinkManagerImplementationTests

package edu.oakland.test.middleware02 {
    class MiddlewareCommLinkManagerImplementationTests {
        + void rfidDoesNotMatchStopsTestCase()
        + void storeRequestSentWhenRfidsMatch()
        + void doesNotStoreRequestSentWhenRfidsDoNotMatch()
        + void doesNotStoreRequestSentWhenNotInNormalMode()
        + void emptyDatabaseReturnsEmptyTrackData()
        + void notEnoughDataReturnsPartialTrackData()
        + void enoughTrackDataReturnsFullData()
        + void storedTrackDataCheck()
        + void nullMiddwareCommDatabaseInterfaceIsNotAllowed()
        + void nullMiddwareGisManagerIsNotAllowed()
        - LocationDataPoint generateRandomLocationDataPoint()
        - LocationDataPoint[] generateRandomLocationDataPointsArray(int length)
    }
}

@enduml
