@startuml MiddlewareGisManagerImplementationTests

package edu.oakland.test.middleware01 {
  class MiddlewareGisManagerImplementationTests {
    + void nullLocationDataPointNotStored()
    + void isGpsSignalStrengthEvaluateTrue()
    + void isGpsSignalStrengthEvaluateFalse()
    + void ldpInIsLdpOut()
    + void enterDegradedFromNormal()
    + void enterNormalFromDegraded()
    + void enterStandbyFromNormal()
    + void enterDegradedFromStandby()
    + void enterStandbyFromStandby()
    + void databaseInterfaceIsNotNull()
  }
}

@enduml
