@startuml MiddlewareGisManagerImplementationTests

package edu.oakland.test.middleware01 {
  class MiddlewareGisManagerImplementationTests {
    + void nullLocationDataPointNotStored()
    + void isGpsSignalStrengthEvaluateTrue()
    + void isGpsSignalStrengthEvaluateFalse()
    + void ldpInIsLdpOut()
    + void isNormalModeEntered()
    + void isStandbyModeEntered()
    + void isDegradedModeEntered()
    + void databaseInterfaceIsNotNull()
  }
}

@enduml
