@startuml MiddlewareGisManagerImplementationTests

package edu.oakland.test.middleware01 {
  class MiddlewareGisManagerImplementationTests {
    + void nullLocationDataPointNotStored()
    + void isGpsLockRegained()
    + void isGpsSignalStrengthEvaluate()
    + void isCorrectModeEntered()
    + void selectNewGps()
    + void databaseInterfaceIsNotNull()
  }
}

@enduml
