@startuml CompleteClosure

!include admin/AdminPackages.puml
!include display01/Display01Packages.puml
!include display02/Display02Packages.puml
!include middleware01/Middleware01Packages.puml
!include middleware02/Middleware02Packages.puml
!include database/DatabasePackages.puml

@enduml