@startuml TrackDataCalculatorTests

package edu.oakland.test.middleware02 {
    class TrackDataCalculatorTests {
      + void calculateSpeedTest()
      + void calculateDirectionTest()
      + void trackDataCalculatorIsConstructable()
      - void calculateRootMeanSquaredTest()
    }
}

@enduml