@startuml DatabaseCommInterface

package edu.oakland.production.database {
    interface DatabaseCommInterface {
    	- DatabaseCommManager databaseCommManager
    	- int rfidData
    	- LocationDataPoint locDataPoint
    	- TrackData trackData
    	- String mode
        __
        DatabaseCommInterface(int rfidData, 
        \tLocationDataPoint locDataPoint,
        \tTrackData trackData)
        .. Use Case 1 ..
        + int receiveGetRfidRequest()
        + LocationDataPoint receiveGetLocationDataPointRequest(int offset)
        + TrackData receiveGetTrackDataRequest(int offset)
        + void storeTrackDataRequest(TrackData trackData)
        + String receiveGetModeRequest()
        
    }
}

@enduml