@startuml TrackDataPlotter

package edu.oakland.helper.display02 {
    class TrackDataPlotter {
        - TrackData data
        - XYSeries points
        - XYSeries fitLine
        - JFreeChart chart
        __
        + TrackDataPlotter(TrackData data)
        .. Use Case 1 ..
        + void displayChart()
        + boolean getDisplayeChart()
        - XYSeries getTrackData()
        - XYSeries calculateLine(int[] x, int[] y)
        - float[] extractLatFromTrackData(TrackData data)
        - float[] extractLngFromTrackData(TrackData data)
        - JFreeChart createChart()
    }
}

@enduml
