@startuml DisplayGpsInterfaceImplementationTests

package edu.oakland.test.display01 {
    class DisplayGpsInterfaceImplementationTests {
      + void verifyReceiverCannotBeNull()
      + void signalInIsSignalOut()
      + void satelliteInIsSatelliteOutReportLoss()
      + void satelliteInIsSatelliteOutCheck()
      + void satelliteInIsSatelliteOutRecheck()
    }
}

@enduml