@startuml DisplayGpsManagerImplementationTests

package edu.oakland.test.display01 {
    class DisplayGpsManagerImplementationTests {
        + void receivedGpsSignalStrengths()
        + void recheckGpsSignalStrength()
        + void checkGpsSignalStrength()
        + void middlewareGisIsNotNull()
    }
}

@enduml
