@startuml DisplayGpsManagerImplementationTests

package edu.oakland.display01.tests {
    class DisplayGpsManagerImplementationTests {
        + void receivedGpsSignalStrengths()
        + void ifAcceptableGpsSignalStrengths()
        + void elsePoorGpsSignalStrengths()
        + 
    }
}

@enduml
