@startuml DisplayGpsInterface

package edu.oakland.production.display01 {
    interface DisplayGpsInterface {
        __
        .. Use Case 1 ..
        {abstract} + String receiveGpsSignal(Satellite satelliteSignal)
        .. Use Case 2 ..
        {abstract} + SatelliteSignalCheckRequest reportGpsSignalLoss(Satellite satelliteSignal)
        {abstract} + SatelliteSignalCheckRequest recheckSignalStength(Satellite satelliteSignal)
        {abstract} + SatelliteSignalCheckRequest checkSignalStength(Satellite satelliteSignal)
    }
}

@enduml
