@startuml DatabaseGisInterfaceStub

package edu.oakland.test.middleware01 {
    class DatabaseGisInterfaceStub {
        __
        .. Use Case 1 ..
        + void receiveStoreRequest(LocationDataPoint locationDataPoint)
        + LocationDataPoint getLocation()
        .. Use Case 2 ..
        + void receiveModeRequest(String mode)
        + String getMode()
        + String receiveNextSatRequest(String currentSat)
    }
}

@enduml