@startuml MiddlewareGisManagerImplementation

package edu.oakland.production.middleware01 {
    class MiddlewareGisManagerImplementation {
        - MiddlewareGisProcessor middlewareGisProcessor
        __
        + MiddlewareGisManagerImplementation(MiddlewareGisProcessor middlewareGisProcessor)
        .. Use Case 1 ..
        + String receieveGpsSignalStrength(Satellite satelliteSignal)
        + void storeLocationDataPoint()
        .. Use Case 2 ..
        + String attemptToRegainGpsLock(String satelliteName)
        + String evaluateGpsSignalStrength(boolean signalValid)
    }
}

@enduml