@startuml DisplayGpsInterfaceStub

package edu.oakland.test.admin {
    class DisplayGpsInterfaceStub {
        __
        .. Use Case 1 ..
        + String receiveGpsSignal(Satellite satelliteSignal)
        .. Use Case 2 ..
        + SatelliteSignalCheckRequest reportGpsSignalLoss(String satelliteSignal)
        + SatelliteSignalCheckRequest recheckSignalStength(String satelliteSignal)
        + SatelliteSignalCheckRequest checkSignalStength(String satelliteSignal)
    }
}

@enduml
