@startuml DisplayGpsManagerImplementation

package edu.oakland.production.display01 {
  class DisplayGpsManagerImplementation {
    - MiddlewareGisInterface gisInterface
   __
    + DisplayGpsManagerImplementation(MiddlewareGisInterface gisInterface)
    .. Use Case 1 ..
    + String receiveGpsSignalStrength(Satellite satelliteSignal)
    .. Use Case 2 ..
    + SatelliteSignalCheckRequest passGpsSignalStrength(Satellite satelliteSignal)
    }
}

@enduml