@startuml DisplayCommInterfaceImplementation

package edu.oakland.production.display02 {
    class DisplayCommInterfaceImplementation {
        - DisplayComm2WayInterface comm2Way
        __
        + DisplayCommInterface(DisplayComm2WayInterface displayComm2WayInterface)
        .. Use Case 1 ..
        + TrackData receiveRfidRequest(int rfidNum)
        
    }
}

@enduml
