@startuml DisplayCommInterfaceImplementation

package edu.oakland.production.display02 {
    class DisplayCommInterfaceImplementation {
        - DisplayComm2WayInterface receiver
        - TrackData data
        - TrackDataPlotter plotter
        __
        + DisplayCommInterface(DisplayComm2WayInterface receiver)
        .. Use Case 1 ..
        + TrackData receiveRfidRequest(int rfidNum)
        
    }
}

@enduml
