@startuml DisplayCommInterfaceImplementation

package edu.oakland.production.display02 {
    class DisplayCommInterfaceImplementation {
        DisplayComm2WayInterface receiver
        __
        {abstract} + DisplayCommInterface(DisplayComm2WayInterface receiver)
        .. Use Case 1 ..
        {abstract} + TrackData receiveRfidRequest(int rfidNum)
        {abstract} + TrackData passToComm2WayInterface(int rfidNum)

    }
}

@enduml
