@startuml DisplayComm2WayInterfaceImplementation

package edu.oakland.production.display02 {
    class DisplayComm2WayInterfaceImplementation {
        - DisplayCommManager commManager
        __
        + DisplayComm2WayInterfaceImplementation(DisplayCommManager commManager)
        .. Use Case 1 ..
        + TrackData passRfidRequest(int rfidNum)
    }
}

@enduml
