@startuml DisplayComm2WayInterfaceImplementation

package edu.oakland.production.display02 {
    class DisplayComm2WayInterfaceImplementation {
        DisplayCommManager manager
        __
        .. Use Case 1 ..
        DisplayComm2WayInterfaceImplementation(DisplayCommManager manager)
        {abstract} + TrackData passRfidRequest(int rfidNum)
        {abstract} + void determineUserRequestFormat(int rfidNum)
        {abstract} + void receiveRequestFromDisplayCommInterface(int rfidNum)
    }
}

@enduml
