@startuml DemoTests

package edu.oakland.test.admin {
    class DemoTests {
        + void configureRfidScannerInputIsUserInput()
        + void configureRfidRfidInIsRfidOut()
        + void configureSatelliteNamesScannerInputIsUserInput()
        + void configureSatelliteNamesSatelliteNamesInAreSatelliteNamesOut()
        + void runUseCasesScannerInputIsUserInput()
        + void runScannerInputIsUserInput()
        + void initSuccessful()
        + void runHandleInvalidMode()
        + void runCanQuit()
        - int generateRandomNumber()
        - int generateRandomStringLength()
        - String[] generateRandomStringArray(int length)
        - String generateRandomString(int length)
    }
}

@enduml
