# This is a basic workflow to help you get started with Actions

name: Gradle Build and Test

# Controls when the action will run. Triggers the workflow on pull request events
on:
  pull_request:
  push:
    branches:
      - "main"
  workflow_dispatch:

# This workflow contains a single job "build"
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo Branch
        uses: actions/checkout@v2

      # Installs the Java JDK
      - name: Install openjdk-11.0.8 (x64)
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8 # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      # Run Gradle Build
      - name: Build and Test with Gradle
        run: ./gradlew build

      # Persist Test Reports
      - name: Persist Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: build/reports/tests/test
          retention-days: 5
      
      # Persist Distributions
      - name: Persist Distributions
        uses: actions/upload-artifact@v2
        with:
          name: Distributions
          path: build/distributions
          retention-days: 5